AllowedOrigins:
# Define origins as a list by explicitly listing origins only. List exact
# domains you trust and never use wildcards in production.
#
# Examples:
# - https://localhost:3000
# - https://127.0.0.1:3000
#
# Do not use wildcards in production— allows ANY origin to call your application:
# - "*"
AllowedMethods:
# add methods as a list
#  - POST
#  - PUT
#  - DELETE
#  - OPTIONS
  - GET
AllowedHeaders:
  - Accept
  - Authorization
  - Content-Type
  - X-CSRF-Token
ExposedHeaders:
  - Link
AllowCredentials: false
MaxAge: 300
